---
abstract: 'Interface to PGXN mirrors and the PGXN API'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  File::Spec::Functions: 0
  Module::Build: 0.30
  Test::MockModule: 0.05
  Test::More: 0.96
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-PGXN
provides:
  WWW::PGXN:
    file: lib/WWW/PGXN.pm
    version: v0.12.1
  WWW::PGXN::Distribution:
    file: lib/WWW/PGXN/Distribution.pm
    version: v0.12.1
  WWW::PGXN::Extension:
    file: lib/WWW/PGXN/Extension.pm
    version: v0.12.1
  WWW::PGXN::Mirror:
    file: lib/WWW/PGXN/Mirror.pm
    version: v0.12.1
  WWW::PGXN::Tag:
    file: lib/WWW/PGXN/Tag.pm
    version: v0.12.1
  WWW::PGXN::User:
    file: lib/WWW/PGXN/User.pm
    version: v0.12.1
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Carp: 0
  File::Spec: 0
  HTTP::Tiny: 0
  JSON: 0
  URI::Template: 0
  perl: 5.01
resources:
  bugtracker: http://github.com/theory/www-pgxn/issues/
  homepage: http://search.cpan.org/dist/WWW-PGXN/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/www-pgxn/tree/
version: v0.12.1
